
services:
  postgres:
    image: postgres:16-alpine
    container_name: diploma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_platform
    ports:
      - '5432:5432'
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d pet_platform']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: diploma-mongo
    restart: unless-stopped
    # 4GB droplet дээр Mongo default cache (~1.4GB) OOM үүсгэж болно.
    command: ['mongod', '--wiredTigerCacheSizeGB', '0.5']
    ports:
      - '27017:27017'
    volumes:
      - diploma_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: diploma-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - diploma_redis_data:/data

volumes:
  diploma_pg_data:
  diploma_mongo_data:
  diploma_redis_data:
