ALTER TABLE pets
  ADD COLUMN IF NOT EXISTS vaccinated BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS neutered BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS spayed BOOLEAN NOT NULL DEFAULT false;
